### ISSUE TITLE
API keys not hidden in dist

### ISSUE THREAD

**Issue by ajitzero** [bolah2009/js-weather#9]
Hi there, I suggest removing the dist folder from the repository since Netlify would build it for you anyway.

Your API key is freely accessible here:

https://github.com/bolah2009/js-weather/blob/8bb0d5930338c7770975794c2aaad83bd2823b15/dist/main.js#L121

Use Netlify Environment variables for this.

**Comment by bolah2009** [comment]
You are totally right!
It was an old project but I would do that now.
Thanks! 🙇‍♂️
